- Resources/Private/CodeTemplates/Extbase/extTables.phpt
- Tests/Fixtures/TestExtensions/test_extension/ext_tables.php
Release: 6.2, 7.4
Resolves: #69613
Change-Id: I0d70a7b47e84990da9f680aad496a53d3c4a3be7
> [TASK] Prepend Vendor name in registerPlugin

- Resources/Private/CodeTemplates/Extbase/extTables.phpt
> [TASK] Remove empty lines in BE module registration

- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/tableName.phpt
- Resources/Private/CodeTemplates/Extbase/Partials/TCA/DateProperty.phpt
- Resources/Private/CodeTemplates/Extbase/Partials/TCA/DateTimeProperty.phpt
- Resources/Private/CodeTemplates/Extbase/Partials/TCA/NativeDateProperty.phpt
- Resources/Private/CodeTemplates/Extbase/Partials/TCA/NativeDateTimeProperty.phpt
- Resources/Private/CodeTemplates/Extbase/Partials/TCA/TimeProperty.phpt
- Resources/Private/CodeTemplates/Extbase/Partials/TCA/TimeSecProperty.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child1.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child2.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child3.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child4.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_main.php
> [TASK] Remove useless checkbox setting from TCA input fields

- Resources/Private/CodeTemplates/Extbase/Tests/ControllerTest.phpt
- Resources/Private/CodeTemplates/Extbase/Tests/DomainModelTest.phpt
- Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Controller/MainControllerTest.php
- Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Domain/Model/Child1Test.php
- Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Domain/Model/Child2Test.php
- Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Domain/Model/Child3Test.php
- Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Domain/Model/Child4Test.php
- Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Domain/Model/MainTest.php
This is just best practise.
Releases: master, 7.6
> [TASK] Call parent setUp() function in unit tests

- Classes/ViewHelpers/Format/IndentViewHelper.php
- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/tableName.phpt
- Resources/Private/CodeTemplates/Extbase/Partials/TCA/PropertiesDefinition.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child1.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child2.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child3.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child4.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_main.php
And fix more indentation issues.
Releases: master, 7.6
> [TASK] Remove superfluous spaces after 'title' of table in TCA

- Tests/Fixtures/TestExtensions/test_extension/Classes/Controller/MainController.php
- Tests/Fixtures/TestExtensions/test_extension/Classes/Domain/Model/Child1.php
- Tests/Fixtures/TestExtensions/test_extension/Classes/Domain/Model/Child2.php
- Tests/Fixtures/TestExtensions/test_extension/Classes/Domain/Model/Child3.php
- Tests/Fixtures/TestExtensions/test_extension/Classes/Domain/Model/Child4.php
- Tests/Fixtures/TestExtensions/test_extension/Classes/Domain/Model/Main.php
- Tests/Fixtures/TestExtensions/test_extension/Classes/Domain/Repository/MainRepository.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/ExtensionBuilder/settings.yaml
- Tests/Fixtures/TestExtensions/test_extension/Documentation.tmpl/Index.rst
TODO: make all years dynamic
Change-Id: I2e6bbaec8b8b274645e5e1ed5a143558b703d655
Releases: 7.6
> Fix hard coded year in fixtures

- Resources/Private/CodeTemplates/Extbase/Tests/ControllerTest.phpt
- Resources/Private/CodeTemplates/Extbase/Tests/DomainModelTest.phpt
- Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Controller/MainControllerTest.php
- Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Domain/Model/MainTest.php
- Tests/Functional/CompatibilityTest.php
Just trying another way to fix the compatibility test
> Liayn deprecated mocks

- Resources/Private/CodeTemplates/Extbase/Tests/ControllerTest.phpt
- Resources/Private/CodeTemplates/Extbase/Tests/DomainModelTest.phpt
- Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Controller/MainControllerTest.php
- Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Domain/Model/MainTest.php
> [TASK] Replace mocking with non-deprecated function calls

- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/tableName.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child1.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child2.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child3.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child4.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_main.php
> [TASK] Adjust TCA for starttime/endtime to match the Core's default

- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/tableName.phpt
- Resources/Private/CodeTemplates/Extbase/Partials/TCA/PropertiesDefinition.phpt
- Resources/Private/CodeTemplates/Extbase/Partials/TCA/TypeField.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child1.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child2.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child3.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child4.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_main.php
> [TASK] Use bool value for exclude field config in TCA

- Classes/Configuration/ExtensionBuilderConfigurationManager.php
- Classes/Controller/BuilderModuleController.php
- Classes/Service/ClassBuilder.php
- Classes/Service/ExtensionSchemaBuilder.php
- Classes/Service/ObjectSchemaBuilder.php
- Tests/Fixtures/ClassParser/ClassWithAlias.php
- Tests/Unit/ExtensionSchemaBuilderTest.php
- Tests/Unit/ObjectSchemaBuilderTest.php
> Fixes #32 (#33)

- Resources/Public/jsDomainModeling/extended/ListField.js
- Resources/Public/jsDomainModeling/wireit/js/Container.js
> Use relative instead of absolute paths

- Classes/Controller/BuilderModuleController.php
> Assign settings in index view

- Resources/Private/CodeTemplates/Extbase/Classes/class.phpt
- Resources/Private/CodeTemplates/Extbase/Partials/Property.htmlt
- Resources/Private/CodeTemplates/Extbase/Partials/TCA/Columns.phpt
- Resources/Private/CodeTemplates/Extbase/Partials/TCA/TypeField.phpt
- Resources/Private/CodeTemplates/Extbase/extEmconf.phpt
> Use new escape flag in fluid

- Resources/Private/CodeTemplates/Extbase/extTables.sqlt
- Tests/Fixtures/TestExtensions/test_extension/ext_tables.sql
> Proposed code for issue #57

- Resources/Private/CodeTemplates/Extbase/extTables.phpt
> Fix categorizable generation

- Resources/Private/CodeTemplates/Extbase/Partials/TCA/Columns.phpt
- Resources/Private/CodeTemplates/Extbase/Partials/TCA/PropertiesDefinition.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_main.php
> Remove mode=ts_css, fixes #60

- Resources/Public/jsDomainModeling/wireit/lib/inputex/lib/yui-rpc.js
- Resources/Public/jsDomainModeling/wireit/lib/yui-rpc.js
Remove broken part
Releases: master, 8.6
> [BUGFIX] Wrong url for save action in backend module

- Classes/Domain/Model/DomainObject.php
- Classes/Service/FileGenerator.php
- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/Overrides/tableName.phpt
- Resources/Private/CodeTemplates/Extbase/extTables.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/Overrides/tx_testextension_domain_model_child3.php
- Tests/Fixtures/TestExtensions/test_extension/ExtensionBuilder.json
> Move makeCategorizable call

- Classes/Service/FileGenerator.php
> Catch error in template exists function

- Classes/Parser/NodeFactory.php
> [BUGFIX] Declare function NodeFactory::buildNodeFromValue static

- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/tableName.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child1.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child2.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child3.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child4.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_main.php
The current definition of starttime and endtime generates a deprecation warning
> Update starttime endtime

- Resources/Private/CodeTemplates/Extbase/Partials/TCA/Columns.phpt
- Resources/Private/CodeTemplates/Extbase/Partials/TCA/PropertiesDefinition.phpt
- Resources/Private/CodeTemplates/Extbase/Partials/TCA/RichTextProperty.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_main.php
The current RTE partial generates a deprecation warning
> Update RTE partial

- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/tableName.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child1.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child2.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child3.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child4.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_main.php
This avoid errors with databases running in strict mode.
Fixes: #63
> [BUGFIX] Define default value for l10n_parent in TCA

- Classes/Domain/Model/DomainObject/AbstractProperty.php
- Resources/Private/CodeTemplates/Extbase/Partials/TCA/PropertiesDefinition.phpt
- Resources/Private/Language/locallang.xlf
- Resources/Public/jsDomainModeling/modules/modelObject.js
> Add 'l10n_mode' to 'show advanced options'

- Classes/Domain/Model/Extension.php
> [BUGFIX] Initialize properties in extension model

- Resources/Public/jsDomainModeling/extbaseModeling.js
- Resources/Public/jsDomainModeling/extended/Group.js
- Resources/Public/jsDomainModeling/wireit/js/WiringEditor.js
- Resources/Public/jsDomainModeling/wireit/js/util/DD.js
TYPO3.jquery has been removed with TYPO3 v9
Fixes: #140
> [TASK] Replace TYPO3.jquery with $

- Resources/Private/Layouts/Default.html
- Resources/Public/jsDomainModeling/extbaseModeling.css
- Resources/Public/jsDomainModeling/extbaseModeling.js
- Resources/Public/jsDomainModeling/extbaseModeling.scss
- Resources/Public/jsDomainModeling/extensionProperties.js
- Resources/Public/jsDomainModeling/wireit/lib/inputex/js/fields/InPlaceEdit.js
> Adapt backend to current master

- Classes/Parser/ClassFactory.php
> Support for parameters by reference

- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/tableName.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child1.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child2.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child3.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child4.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_main.php
> Use doctrine compatible quoting

- Classes/Configuration/ExtensionBuilderConfigurationManager.php
> Adapt ajax method

- Classes/Domain/Model/Extension.php
Replacements need the vendor name
> Task: Resolve composer warning

- Resources/Private/CodeTemplates/Extbase/Resources/Private/Language/locallang.xlft
Fixes regression introduced in https://github.com/FriendsOfTYPO3/extension_builder/commit/5c2544bb1bfe8e3898581786d0333ba350c98c28
> [BUGFIX] Deleted additional quote from resname attribute

- Classes/Service/FileGenerator.php
- Tests/Fixtures/TestExtensions/test_extension/ext_tables.sql
> Add postprocessing of ext_tables.sql

- Classes/Service/FileGenerator.php
- Resources/Private/CodeTemplates/Extbase/gitattributes.t
Exclude those files in zip archive whenever the generated extension is fetched via composer.
> [TASK] Add .gitattributes file to exclude files for composer installations

- Classes/Service/ClassBuilder.php
> [BUGFIX] Properly escape regexp literals when used as regular values

- Documentation/Configuration/Index.rst
- Documentation/Developer/Roundtrip.rst
- Documentation/Introduction/Index.rst
- Documentation/User/Index.rst
Apply the changes from Franz Holzinger to master
> Wording fixes

- .github/workflows/tests.yml
- composer.json
This update enables us to additionally also test with sqlite database. Should I add those tests as well as github action?
> [TASK] Update nimut/testing-framework and switch to sqlite database tests

- Classes/Service/RoundTrip.php
resolves #287
should also be backported to master
> Convert CamelCase relation name for TCA

- Classes/Domain/Model/DomainObject/Relation/AbstractRelation.php
> [BUGFIX] Make property foreignModel of Class AbstractRelation nullable again

- Documentation/Developer/Index.rst
The extension key can have an underline character "_ " inside of its name.
> small changes, "backend" is kept

- Classes/Domain/Model/Extension.php
> Transform vendor name for composer info

- Resources/Private/CodeTemplates/Extbase/extTables.sqlt
- Tests/Fixtures/TestExtensions/test_extension/ext_tables.sql
The comments do not convey any more information than the SQL below already does.
> [TASK] Remove useless SQL comments

- Classes/Service/ClassBuilder.php
- Resources/Private/CodeTemplates/Extbase/Classes/Domain/Model/Model.phpt
- Resources/Private/CodeTemplates/Extbase/Partials/Classes/Model/Methods/constructMethodBody.phpt
- Tests/Fixtures/TestExtensions/test_extension/Classes/Domain/Model/Main.php
- Tests/Functional/FileGeneratorTest.php
See also https://forge.typo3.org/issues/83386
Resolves: #312
> [BUGFIX] Use initializeObject to reconstruct models correctly

- Classes/Parser/Utility/NodeConverter.php
> Fix exception in NodeConverter when methods contain nullable types

- Classes/Configuration/ExtensionBuilderConfigurationManager.php
- Classes/Controller/BuilderModuleController.php
- Classes/Domain/Model/DomainObject.php
- Classes/Domain/Model/DomainObject/AbstractProperty.php
- Classes/Service/ClassBuilder.php
- Classes/Service/ExtensionSchemaBuilder.php
- Classes/Service/FileGenerator.php
- Classes/Service/RoundTrip.php
- Resources/Private/CodeTemplates/Extbase/Configuration/Extbase/Persistence/Classes.phpt
- Tests/BaseFunctionalTest.php
- Tests/BaseUnitTest.php
- Tests/Fixtures/TestExtensions/test_extension/ExtensionBuilder.json
- Tests/Functional/CompatibilityTest.php
- Tests/Unit/ExtensionSchemaBuilderTest.php
Adaptions to this breaking change: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html
> Persistence classes

- Resources/Public/jsDomainModeling/extbaseModeling.css
- Resources/Public/jsDomainModeling/extbaseModeling.scss
> Fix various margins & positions

- Resources/Public/jsDomainModeling/extended/ListField.js
- Resources/Public/jsDomainModeling/wireit/js/Container.js
- Resources/Public/jsDomainModeling/wireit/lib/inputex/js/Field.js
- Tests/Fixtures/TestExtensions/test_extension/composer.json
- composer.json
> [BUGFIX] Adjust icon paths and require according Core version

- Classes/ViewHelpers/RecordTypeViewHelper.php
> Skip getRecordType if parent class is empty

- Resources/Private/CodeTemplates/Extbase/extTables.phpt
- Tests/Fixtures/TestExtensions/test_extension/ext_tables.php
- ext_tables.php
> Remove TYPO3_MODE usage from ext_tables

- Classes/Service/FileGenerator.php
- Classes/Service/RoundTrip.php
Use constants for overwrite settings
Resolves #354
> Remove superfluous slash in Persistence Class path

- Classes/Utility/ExtensionInstallationStatus.php
It was a mess to find this information:
https://github.com/FriendsOfTYPO3/extension_builder/issues/351#issuecomment-784965212
What do you think about this additional info?
> More information how to install the EXT in composer mode

- Resources/Private/CodeTemplates/Extbase/extEmconf.phpt
- Tests/Fixtures/TestExtensions/test_extension/ext_emconf.php
- ext_emconf.php
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/DeclarationFile/Index.html
> remove deleted createDirs

- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/tableName.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child1.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child2.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child3.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child4.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_main.php
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Feature-88901-RenderAllFieldsInElementInformationController.html
> showrecordfieldlist is deprecated

- Classes/Domain/Model/AbstractObject.php
- Classes/Parser/ClassFactory.php
- Tests/Fixtures/ClassParser/SimpleProperty.php
Solves these issues:
1. license header should not be added to class object description
2. first write and rewrite should have equal comments
> Refactor doc comment header

- Classes/Service/ObjectSchemaBuilder.php
> [BUGFIX] Cast string to integer for File maxItems setting

- Classes/Domain/Validator/ExtensionValidator.php
> [BUGFIX] Don't allow related models containing a duplicated property

- Classes/Domain/Model/DomainObject/Action.php
- Classes/Service/FileGenerator.php
- Classes/Service/ObjectSchemaBuilder.php
- Resources/Private/CodeTemplates/Extbase/Resources/Private/Templates/custom.htmlt
- Tests/Unit/ObjectSchemaBuilderTest.php
> [FEATURE] Custom action should also create a template file

- Classes/Service/RoundTrip.php
- ext_conf_template.txt
> [BUGFIX] Use backup dir under var/

- Resources/Public/jsDomainModeling/modules/modelObject.js
> [BUGFIX] Deny relation to relation wires

- Documentation/Developer/Index.rst
Do not scare developers by using the advanced mode
> [DOCS] Remove misconfiguration hint

- Classes/Service/FileGenerator.php
- Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Language/locallang.xlf
- Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Language/locallang_csh_tx_testextension_domain_model_child1.xlf
- Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Language/locallang_csh_tx_testextension_domain_model_child2.xlf
- Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Language/locallang_csh_tx_testextension_domain_model_child3.xlf
- Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Language/locallang_csh_tx_testextension_domain_model_child4.xlf
- Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Language/locallang_csh_tx_testextension_domain_model_main.xlf
- Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Language/locallang_db.xlf
- Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Language/locallang_testmodule1.xlf
and add missing file extension in all locallang files
> Attribute original in locallang_csh is missing tablename

- Classes/Domain/Model/Extension.php
- Classes/Service/ExtensionSchemaBuilder.php
- Classes/Service/FileGenerator.php
- Resources/Private/Language/locallang.xlf
- Resources/Public/jsDomainModeling/extended/Group.js
- Resources/Public/jsDomainModeling/extensionProperties.js
- Tests/Fixtures/TestExtensions/test_extension/ExtensionBuilder.json
- Tests/Functional/FileGeneratorTest.php
> [FEATURE] Make generating of git related files configurable

- Classes/Domain/Model/Extension.php
- Classes/Service/ExtensionSchemaBuilder.php
- Classes/Service/FileGenerator.php
- Resources/Private/CodeTemplates/Extbase/editorconfig.t
- Resources/Private/Language/locallang.xlf
- Resources/Public/jsDomainModeling/extensionProperties.js
- Tests/Functional/FileGeneratorTest.php
> [FEATURE] Make generating of editorconfig file configurable

- Classes/Domain/Model/DomainObject.php
- Classes/Domain/Model/DomainObject/AbstractProperty.php
- Classes/Domain/Model/DomainObject/Relation/ZeroToManyRelation.php
- Classes/Service/ClassBuilder.php
- Classes/Service/RoundTrip.php
> [BUGFIX] Removing domain property annotations again when not needed

- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/tableName.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child1.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child2.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child3.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child4.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_main.php
add new tab 'language' for language fields
> [TASK] Restructure form elements in backend

- .github/workflows/check-commit-message.yml
> [TASK] Add a github action to test the commit message

- Classes/Parser/ClassFactory.php
- Tests/Unit/Parser/ClassFactoryTest.php
> [BUGFIX] Fix models that implement an interface class generation

- .github/workflows/tests.yml
- Classes/Domain/Model/Extension.php
- Configuration/Services.yaml
- Documentation/Settings.cfg
- README.md
- Resources/Public/jsDomainModeling/extensionProperties.js
- Tests/BaseFunctionalTest.php
- Tests/BaseUnitTest.php
- Tests/Fixtures/TestExtensions/test_extension/ExtensionBuilder.json
- Tests/Fixtures/TestExtensions/test_extension/composer.json
- Tests/Fixtures/TestExtensions/test_extension/ext_emconf.php
- composer.json
- ext_emconf.php
> [TASK] Generate TYPO3 11 dependent extension

- Classes/Controller/BuilderModuleController.php
- Classes/Domain/Model/FunctionObject.php
- Classes/Parser/ClassFactory.php
- Classes/Parser/NodeFactory.php
- Classes/Service/Printer.php
- Resources/Private/CodeTemplates/Extbase/Classes/Controller/Controller.phpt
- Tests/Fixtures/TestExtensions/test_extension/Classes/Controller/MainController.php
> [TASK] Extbase controller actions must return ResponseInterface

- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/Overrides/sys_template.phpt
- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/Overrides/tableName.phpt
- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/Overrides/tt_content.phpt
- Resources/Private/CodeTemplates/Extbase/extLocalconf.phpt
- Resources/Private/CodeTemplates/Extbase/extTables.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/Overrides/sys_template.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/Overrides/tt_content.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/Overrides/tx_testextension_domain_model_child3.php
- Tests/Fixtures/TestExtensions/test_extension/ext_localconf.php
- Tests/Fixtures/TestExtensions/test_extension/ext_tables.php
- ext_tables.php
> [TASK] Replace TYPO3_MODE and TYPO3_REQUESTTYPE constants

- Classes/Controller/BuilderModuleController.php
> [FEATURE] Introduce ForwardResponse for extbase

- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/tableName.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_category.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child1.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child2.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child3.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child4.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_main.php
> [FEATURE] New TCA type "language"

- Resources/Private/CodeTemplates/Extbase/extTables.sqlt
- Tests/Fixtures/TestExtensions/test_extension/ext_tables.sql
> [FEATURE] Auto creation of MM tables from TCA

- Classes/Service/FileGenerator.php
- Resources/Private/CodeTemplates/Extbase/Configuration/Icons.phpt
- Resources/Private/CodeTemplates/Extbase/extLocalconf.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/Icons.php
- Tests/Fixtures/TestExtensions/test_extension/ext_localconf.php
- Tests/Functional/Service/FileGeneratorTest.php
> [FEATURE] Registering Icons via Service Container

- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/Overrides/tableName.phpt
- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/tableName.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/Overrides/tx_testextension_domain_model_child3.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child3.php
> [FEATURE] New TCA type "category"

- Classes/Configuration/ExtensionBuilderConfigurationManager.php
- Classes/Service/ExtensionService.php
- Classes/Service/RoundTrip.php
> [TASK] Replace deprecated GeneralUtility::isAbsPath

- Classes/Configuration/ExtensionBuilderConfigurationManager.php
> [TASK] Replace deprecated GeneralUtility::isFirstPartOfStr

- Resources/Private/CodeTemplates/Extbase/Tests/Unit/ControllerTest.phpt
- Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Controller/MainControllerTest.php
> [TASK] Replace deprecated ViewInterface

- Classes/Service/ExtensionSchemaBuilder.php
> [BUGFIX] Create documentation template when checked

- Documentation/GeneratedExtension/Index.rst
First proof-read of new documentation, first inconsistency found :)
> [DOCS] Checkbox was renamed to "Generate documentation"

- .github/workflows/tests.yml
- Classes/Service/RoundTrip.php
- Tests/Fixtures/ClassParser/AnotherComplexClass.php
- Tests/Fixtures/ClassParser/ClassMethodWithManyParameter.php
- Tests/Functional/Service/FileGeneratorTest.php
> [TASK] Make Extension Builder compatible with PHP 8.0

- Classes/Service/ClassBuilder.php
- Tests/Fixtures/TestExtensions/test_extension/Classes/Domain/Model/Category.php
- Tests/Fixtures/TestExtensions/test_extension/Classes/Domain/Model/Child1.php
- Tests/Fixtures/TestExtensions/test_extension/Classes/Domain/Model/Child2.php
- Tests/Fixtures/TestExtensions/test_extension/Classes/Domain/Model/Child3.php
- Tests/Fixtures/TestExtensions/test_extension/Classes/Domain/Model/Child4.php
- Tests/Fixtures/TestExtensions/test_extension/Classes/Domain/Model/Main.php
> [TASK] Update return type hint for model getters

- Documentation/Includes.rst.txt
- Documentation/Index.rst
- Documentation/Settings.cfg
- Documentation/Sitemap.rst
- Documentation/genindex.rst
- README.rst
Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/182
> [TASK] Align with new TYPO3 documentation standards

- Classes/Controller/BuilderModuleController.php
- Classes/Service/ExtensionService.php
- Classes/Service/RoundTrip.php
This PR fixes 2 issues when using the extension with `typo3/cms-composer-installers` version 4. 
#594
> [TASK] Add support for typo3/cms-composer-installers v4

- Resources/Public/jsDomainModeling/extbaseModeling.js
Fix issue while adding relations to an entity
Reverted the code from previous bugfix
> [BUGFIX] Fix issue in JS - "Relations"

- Resources/Private/CodeTemplates/Extbase/Partials/TCA/FileProperty.phpt
- Resources/Private/CodeTemplates/Extbase/Partials/TCA/ImageProperty.phpt
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child3.php
- Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child4.php
> [BUGFIX] Generate correct TCA for images and files

- Classes/Parser/Utility/NodeConverter.php
add branch to specify Node\Identifier type resolution
fixes: https://github.com/FriendsOfTYPO3/extension_builder/issues/629
> [BUGFIX] resolve nullable types correctly

- Classes/Domain/Model/Extension.php
> [BUGFIX] - Undefined array key - check whether the array key $parentClass exists or not

- Classes/Domain/Model/ClassObject/ClassObject.php
- Classes/Domain/Model/Extension.php
- Classes/Parser/NodeFactory.php
- Tests/BaseFunctionalTest.php
- Tests/Fixtures/TestExtensions/test_extension/composer.json
- composer.json
> [BUGFIX] Fix failing tests

- Classes/Service/ValidationService.php
- Resources/Private/CodeTemplates/Extbase/Configuration/FlexForms/plugin_flexform.phpt
- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/Overrides/tt_content.phpt
- Resources/Private/CodeTemplates/Extbase/Configuration/TCA/tableName.phpt
- Resources/Private/CodeTemplates/Extbase/extEmconf.phpt
- Tests/Fixtures/TestExtensions/test_extension/ext_emconf.php
Resolves: #743, #744, #745, #746
> [TASK] fix several minor issues in TCA and flexfom.
