FriendsOfTYPO3/extension_builder

Classes/Configuration/ExtensionBuilderConfigurationManager.php
Classes/Controller/BuilderModuleController.php
Classes/Domain/Repository/ExtensionRepository.php
Classes/Domain/Validator/ExtensionValidator.php
Classes/Service/ClassBuilder.php
Classes/Service/ExtensionSchemaBuilder.php
Classes/Service/ObjectSchemaBuilder.php
Classes/Service/RoundTrip.php
Classes/ViewHelpers/MappingViewHelper.php
Classes/ViewHelpers/RecordTypeViewHelper.php
Configuration/Backend/AjaxRoutes.php
Tests/BaseFunctionalTest.php
Tests/Functional/CompatibilityTest.php
Tests/Functional/ConfigurationManagerTest.php
Tests/Functional/RoundTripRenameVendorTest.php
Tests/Unit/ClassBuilderTest.php
Tests/Unit/ExtensionSchemaBuilderTest.php
Tests/Unit/ObjectSchemaBuilderTest.php
ext_typoscript_setup.txt

(different approch of fixing it then BenjaminBeck).
Rename ConfigurationManager to ExtensionBuilderConfigurationManager. Not let ExtensionBuilders ConfigurationManager be injected outside. That cause conflicts with flux extension.

[BUGFIX] Prevent using wrong configurationManager implementation.

---

Classes/Domain/Model/Extension.php

The author information is stored in an array authors (plural) not author.
The composer.json scheme is very strict and does not allow additional properties for the authors property. Therefore the company entry is removed for each author.
`$ composer validate` is now passed.

[BUGFIX] Create valid composer.json

---

Resources/Private/CodeTemplates/Extbase/Tests/DomainModelTest.phpt

Ensures unit tests has methods for integer properties.
Resolves: #66
Releases: master

[BUGFIX] DomainModel UnitTests missing for integer properties

---

Classes/Domain/Model/DomainObject/NativeDateProperty.php
Classes/Domain/Model/DomainObject/NativeDateTimeProperty.php
Resources/Private/CodeTemplates/Extbase/Partials/TCA/NativeDateProperty.phpt
Resources/Private/CodeTemplates/Extbase/Partials/TCA/NativeDateTimeProperty.phpt
Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child2.php
Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_main.php
Tests/Fixtures/TestExtensions/test_extension/ext_tables.sql

The used default value for date types `0000-00-00` might lead to errors
using MySQL 5.7 which uses `NO_ZERO_DATE` in `sql_mode` per default.
To solve this issue the default value is defined to be `NULL`.
see https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date
Fixes: #113

[BUGFIX] Fix MySQL `date DEFAULT '0000-00-00'` issues

---

Tests/Fixtures/TestExtensions/test_extension/Configuration/TypoScript/setup.ts

Once persistence.storagePid is set, the manual assignment of a "Record Storage Folder" in the Backend won't have any effect anymore. 
This is confusing, because a simple extension having "Record Storage Folder" assigned manually in the BE, can work work out of the box. But as soon as the automatically generated TypoScript is incorporated, no records are shown any more  - because as soon as there is a Typoscript "persistence.storagePid =" [empty] is assigned.

Add a warning comment and a link concerning the usage persistence.storagePid

---

Resources/Private/CodeTemplates/Extbase/Configuration/TCA/tableName.phpt
Resources/Private/CodeTemplates/Extbase/Partials/TCA/BooleanProperty.phpt
Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child1.php
Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child2.php
Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child3.php
Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child4.php
Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_main.php

Replace deprecated references to locallang_core 
(EXT:lang/locallang_core.xlf => EXT:lang/Resources/Private/Language/locallang_core.xlf)
in 8.7-branch to get rid of deprecation-warnings.

Update deprecated references to EXT:lang/locallang_core.xlf

---

Classes/Service/FileGenerator.php
Tests/Functional/FileGeneratorTest.php

Fixes #189
This PR changes the default file extension for TypoScript files from ".ts" to ".typoscript" as per the [Core recommendation](https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.7.x/Feature-78161-IntroduceTypoScriptFileExtension.html).
In order to not break existing extensions when they are edited with the Extension Builder, the `FileGenerator` will give precedence to existing `.ts` files if they are present.

Use ".typoscript" instead of ".ts" for TypoScript files

---

Classes/Service/RoundTrip.php

When you change a property with a getter and setter method, where the setter method does not have a @return-Tag, you'll get an exception while saving in round-trip mode.
Fixed #216

Fixed round-trip error for method without `@return` tag

---

Classes/Domain/Model/Extension.php
Classes/Service/FileGenerator.php
Classes/ViewHelpers/ListForeignKeyRelationsViewHelper.php
Resources/Private/CodeTemplates/Extbase/Partials/TCA/ManyToOneRelation.phpt
Resources/Private/CodeTemplates/Extbase/Partials/TCA/ZeroToManyRelation.phpt
Resources/Private/CodeTemplates/Extbase/Partials/TCA/ZeroToOneRelation.phpt
Resources/Private/CodeTemplates/Git/HEAD
Resources/Private/CodeTemplates/Git/config
Resources/Private/CodeTemplates/Git/description
Resources/Private/CodeTemplates/Git/info/exclude
Resources/Public/jsDomainModeling/extbaseModeling.css
Resources/Public/jsDomainModeling/extbaseModeling.js
Tests/Fixtures/TestExtensions/test_extension/ExtensionBuilder.json

+ 1:1: `inline` previously, existing `selectSingle` did not work
+ now it's `inline` (aggregate), `selectSingle`, `selectMultipleSideBySide`
+ *:1: `selectSingle` previously
+ now it's `selectSingle`, `selectMultipleSideBySide`
+ 1:*: `inline` previously
+ now it's `inline` (composite), `selectMultipleSideBySide`
This way it shall be possible to make use of different render types.

[FEATURE] Allow different relation render types

---

Classes/Domain/Model/DomainObject/Relation/AbstractRelation.php
Classes/Service/ObjectSchemaBuilder.php

* image properties implicitly have been treated as “inline”
* re-apply default SQL definition for 1:n relationships

[BUGFIX] Ensure type inline is handled correctly

---

Classes/Service/ObjectSchemaBuilder.php

Instead of using implicit "inline" for external class references selected renderType is applied as well.

[BUGFIX] Apply renderType to external class references

---

Documentation/Introduction/Index.rst

An extension is not installed any more, but activated.

small modifications

---

Resources/Private/CodeTemplates/Extbase/extLocalconf.phpt
Resources/Private/CodeTemplates/Extbase/extTables.phpt
Tests/Fixtures/TestExtensions/test_extension/ext_localconf.php
Tests/Fixtures/TestExtensions/test_extension/ext_tables.php

See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.1/Deprecation-88995-CallingRegisterPluginWithVendorName.html

Omit vendor name when registering plugins & modules

---

Resources/Private/CodeTemplates/Extbase/extLocalconf.phpt

Changes in extLocalconf.phpt for creation of ext_localconf.php according to 
"Deprecation: #87550 - Use controller classes when registering plugins/modules", see:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-87550-UseControllerClassesWhenRegisteringPluginsmodules.html
I did run into this issue, when saving plugins with extension_builder 9.11.0. The registration of the controller(s) failed. With this change it now works here at least.

Update extLocalconf.phpt for using controller classes

---

Resources/Public/jsDomainModeling/extensionProperties.js

set the targetVersion and dependsOn to TYPO3 10.4.x.
For targetVersion no further selectOptions/selectValues are needed (i.e. TYPO3 v 9.5) since extensions saved with the extension_builder 9.11.0 will not work in TYPO3 9.5.x anymore (caused by the changes in the plugin configuration).

targetVersion/dependsOn changed to TYPO3 10.4.x

---

Classes/Service/ClassBuilder.php
Tests/Fixtures/TestExtensions/test_extension/Classes/Controller/MainController.php

Changes `@ignorevalidation` according to [Feature: #83094 - Replace @ignorevalidation with @TYPO3\CMS\Extbase\Annotation\IgnoreValidation](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Feature-83094-ReplaceIgnorevalidationWithTYPO3CMSExtbaseAnnotationIgnoreValidation.html).

Replacement of @ignorevalidation

---

Resources/Private/CodeTemplates/Extbase/extLocalconf.phpt
Tests/Fixtures/TestExtensions/test_extension/ext_localconf.php

This should fix #296 .
The controllers will be registered correctly now also in case you will not specify you controllers and actions under "Front end plugins" -> "Advanced options".

Fix for controller registration in extLocalconf

---

Resources/Private/CodeTemplates/Extbase/Resources/Private/Backend/Templates/edit.htmlt
Resources/Private/CodeTemplates/Extbase/Resources/Private/Backend/Templates/list.htmlt
Resources/Private/CodeTemplates/Extbase/Resources/Private/Backend/Templates/new.htmlt
Resources/Private/CodeTemplates/Extbase/Resources/Private/Backend/Templates/show.htmlt
Resources/Private/CodeTemplates/Extbase/Resources/Private/Templates/edit.htmlt
Resources/Private/CodeTemplates/Extbase/Resources/Private/Templates/list.htmlt
Resources/Private/CodeTemplates/Extbase/Resources/Private/Templates/new.htmlt
Resources/Private/CodeTemplates/Extbase/Resources/Private/Templates/show.htmlt
Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Backend/Templates/Main/Edit.html
Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Backend/Templates/Main/List.html
Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Backend/Templates/Main/New.html
Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Backend/Templates/Main/Show.html
Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Templates/Main/Edit.html
Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Templates/Main/List.html
Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Templates/Main/New.html
Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Templates/Main/Show.html

In the explanation example within the template files the name of the object was missing.
For backend modules the backend directory part was also missing in the example.
Only a minor correction but perhaps useful for beginners with extension builder.
I did the change for v10-compatibility branch but it probably may also be merged into master.

Add missing controller name in configuration to keep the templates

---

Resources/Private/CodeTemplates/Extbase/Partials/Form/BooleanProperty.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/DateProperty.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/DateTimeProperty.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/EmailProperty.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/FloatProperty.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/IntegerProperty.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/NativeDateProperty.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/NativeDateTimeProperty.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/PasswordProperty.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/Relation_ManyToManyRelation.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/Relation_ZeroToManyRelation.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/Relation_ZeroToOneRelation.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/RichTextProperty.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/SelectProperty.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/StringProperty.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/TextProperty.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/TimeProperty.htmlt
Resources/Private/CodeTemplates/Extbase/Partials/Form/TimeSecProperty.htmlt
Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Backend/Partials/Main/FormFields.html
Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Partials/Main/FormFields.html

There was no id-attribute for the label-connection in the new/edit Formfield.html Partial:
<label for="company">
<f:translate key="tx_erpcustomer_domain_model_customer.company" />
</label><br />
<f:form.textfield property="company" /><br />
Now it works:
<label for="company">
<f:translate key="tx_erpcustomer_domain_model_customer.company" />
</label><br />
<f:form.textfield property="company" id="company" /><br />

[BUGFIX] add missing id attribute to HTML templates

---

Classes/Parser/Utility/NodeConverter.php

Backport of commit ID a250d638a9 to fix issue when saving extension due
to a PHP warning ("First parameter must either be an object or the name
of an existing class").
Issue caused by a new(er) version of [nikic/php-parser](https://packagist.org/packages/nikic/php-parser).
Resolves: #339

[BUGFIX] Check object before checking property

---

Classes/Service/ExtensionService.php

EB should never write to typo3conf/ext when the instance is setup with composer.

[BUGFIX] Do not offer typo3conf/ext when in composer mode

---

Resources/Private/CodeTemplates/Extbase/Configuration/TCA/tableName.phpt
Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child1.php
Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child2.php
Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child3.php
Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child4.php
Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_main.php

The "t3ver_label" fields are not used anymore in TYPO3 10 since
https://review.typo3.org/c/Packages/TYPO3.CMS/+/59297/
Adding this field to TCA could cause SQL errors in the backend.

[TASK] Remove "t3ver_label" fields

---

Classes/Service/ObjectSchemaBuilder.php

The Checkbox in the ExtBuilder FE `Is l10n_mode` didn't did anything because it wasn't settet aynwhere.
Added the `isset` check and call for `setL10nModeExclude`.

Added setL10nModeExclude call for l10mode exclude flag

---

Classes/Controller/BuilderModuleController.php

Warning shows up when a repository is configured in composer.json.
Should show up when no repository is configured.

Show warning when no repository is configured

---

Classes/Domain/Model/Extension.php

Till today I'm getting this warning for several extension:
```
TYPO3 Extension Package "yoast-seo-for-typo3/yoast_seo", does not define extension key in composer.json.
Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)
```

Add section 'extra' because of composer warning

---

Classes/Domain/Validator/ExtensionValidator.php
Documentation/Developer/Index.rst

Why is it not allowed to write an extension like tt_news or tt_products using the extension builder?

Remove the extension key check 'tt_' prefix

---

Resources/Private/CodeTemplates/Extbase/Resources/Private/Backend/Layouts/default.htmlt
Resources/Private/CodeTemplates/Extbase/Resources/Private/Backend/Templates/edit.htmlt
Resources/Private/CodeTemplates/Extbase/Resources/Private/Backend/Templates/list.htmlt
Resources/Private/CodeTemplates/Extbase/Resources/Private/Backend/Templates/new.htmlt
Resources/Private/CodeTemplates/Extbase/Resources/Private/Backend/Templates/show.htmlt
Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Backend/Layouts/Default.html
Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Backend/Templates/Main/Edit.html
Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Backend/Templates/Main/List.html
Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Backend/Templates/Main/New.html
Tests/Fixtures/TestExtensions/test_extension/Resources/Private/Backend/Templates/Main/Show.html

The layout was inspired by EXT:beuser backend module.
To keep the template simple, the pagePath and pageInfo has been removed.
Closes #337

[BUGFIX] Make backend module templates compatible with TYPO3 10

---

Classes/Domain/Validator/ExtensionValidator.php

It does not make any sense to use the parentClass if it does not exist.

[BUGFIX] Check first if the parent class exists

---

Resources/Private/CodeTemplates/Extbase/Configuration/TypoScript/setup.typoscriptt
Tests/Fixtures/TestExtensions/test_extension/Configuration/TypoScript/setup.typoscript

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Deprecation-89868-RemoveReqCHashFunctionalityForPlugins.html?highlight=requirechashargumentforactionarguments

requireCHashArgumentForActionArguments is deprecated 

---

Resources/Private/CodeTemplates/Extbase/Tests/Functional/BasicTest.phpt
Resources/Private/CodeTemplates/Extbase/Tests/Unit/ControllerTest.phpt
Resources/Private/CodeTemplates/Extbase/Tests/Unit/DomainModelTest.phpt
Tests/Fixtures/TestExtensions/test_extension/Tests/Functional/BasicTest.php
Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Controller/MainControllerTest.php
Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Domain/Model/Child1Test.php
Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Domain/Model/Child2Test.php
Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Domain/Model/Child3Test.php
Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Domain/Model/Child4Test.php
Tests/Fixtures/TestExtensions/test_extension/Tests/Unit/Domain/Model/MainTest.php

Closes #436
References for more info:
- https://github.com/TYPO3/typo3/blob/71c5846cf93148b5ba4cad39bf8a629aa9c05f32/typo3/sysext/extbase/Tests/Unit/Mvc/Controller/ActionControllerTest.php
- https://github.com/TYPO3/testing-framework/pull/161
- https://github.com/sebastianbergmann/phpunit/issues/3338
- https://github.com/sebastianbergmann/phpunit/issues/3338

[FEATURE] Update generated tests to phpunit 9

---

Classes/Controller/BuilderModuleController.php
Resources/Private/Templates/BuilderModule/Domainmodelling.html
Resources/Public/jsDomainModeling/wireit/js/WiringEditor.js

Extension Builder public resource url calculation failed in acceptance tests running in a separate TYPO3 instance at 
```
typo3temp/var/tests/acceptance
```
Calculate the url in the same way as the TYPO3 system extensions.
The previous call `PathUtility::stripPathSitePrefix($extPath)` resolved to
```
typo3temp/var/tests/acceptance/typo3/module/typo3conf/ext/extension_builder
```
instead of 
```
typo3temp/var/tests/acceptance/typo3conf/ext/extension_builder
```
Fixes: #519

[TASK] Adapt public resources url for acceptance tests

---

Classes/Domain/Model/Plugin.php
Classes/Factory/PluginFactory.php

The plugin type was meant to be a switch between list type and content type but this is not in use. For content types the extension Mask should be used.

[TASK] Remove plugin type

---

Documentation/GeneratedExtension/Index.rst
Documentation/GraphicalEditor/Index.rst
Documentation/Settings.cfg
README.rst

- use blog example unit tests instead of dummy unit test
- add "Advanced options" hint in frontend plugin and backend module property descriptions
- apply renaming of "master" branch to "main" of official TYPO3 documentation and repositories
See: #542

[DOCS] Small fixes derived from backport of documentation

---

Documentation/GeneratedExtension/Index.rst
Documentation/GraphicalEditor/Index.rst
Documentation/Introduction/Index.rst
Documentation/PublishToTer/Index.rst
Documentation/Settings.cfg
README.rst

- linked to https://docs.typo3.org/p/... instead of outdated https://docs.typo3.org/typo3cms/extensions/...
- compared the list of prefixes for extension names that are not allowed - in description and implementation
- update hint that the generated extension is symlinked by Composer instead of Extension Builder (both is true, but the first is expected)
- add hint of completing the installation in composer mode by installing the extension in the Extension Manager, prior to TYPO3 v11.4
- list the documentation folder also in the generated extension files of the introduction chapter
- always link to the latest version of the extension publishing guide as the steps do not depend on the TYPO3 compatibility of the generated extension
- explicitly set the versions of the linked documentation to …

[DOCS] Small fixes derived from backport of documentation v11

---

Documentation/Contribution/Index.rst

[DOCS] Rename slack channel to `#extension-builder`

---

composer.json

Added new commit regarding additional sources (TER, repository and docs.typo3.org) in composer.json.
Relates: TYPO3-Documentation/T3DocTeam#185

[TASK] Align with new TYPO3 documentation standards (follow-up)

---

Classes/Service/RoundTrip.php

There is a warning saving a new extension when debug mode is enabled. 
Tested on:
Ubuntu 20.04
PHP 8.1.4

[BUGFIX] Fix PHP8 warning because overwriteSettings not found in empty settings

---

Classes/Service/ClassBuilder.php

On first saving a warning is shown that array key `setDefaultValuesForClassProperties` does not exist

[BUGFIX] Fix warning if setDefaultValuesForClassProperties does not exist

---

Classes/Controller/BuilderModuleController.php
Classes/Template/Components/Buttons/LinkButtonWithId.php
Resources/Private/Language/locallang.xlf

The title of advanced options button had html inside, so the title was displayed faulty.
Fixes #536

[BUGFIX] fixes title for advanced option button

---

Classes/Service/LocalizationService.php

The LocalizationService didn't generate the entries for the plugin name and description.
The variable `$type` is filled with the complete file extension, so it will be `locallang_db.xlf` instead of `locallang_db`.
See this line: https://github.com/FriendsOfTYPO3/extension_builder/blob/c5ba89bfefccf9322b9fecaffb1a3cc1af02f426/Classes/Service/FileGenerator.php#L1182
will fix #603 
will fix #529

[BUGFIX] Generate correct .xlf files

---

Classes/Service/FileGenerator.php

The language files inside Resources/Private/Language were not merged, after saving the extension inside the extension builder. It happened because the suffix was added twice.
will fix #565

[BUGFIX] Language file not merged

---

Documentation/Index.rst

The Extbase Fluid Book has been discontinued. Content that was still of value was moved to TYPO3 explained.
Please backport if possible.

[DOCS] Update Links to the documentation

---

.github/workflows/tests.yml
Classes/Domain/Model/Extension.php
Tests/Fixtures/TestExtensions/test_extension/composer.json
composer.json

To make contribution and maintainance of configuration, scripts etc. for testing easier, we try to use a common standard across TYPO3 extensions.
The current standard is:
- web-dir: .Build/Web
- bin-dir: .Build/bin
- vendor-dir: .Build/vendor
This is used in the official example extensions (tea, docs-examples) as well as in most of the checked community extensions (in a subset of 20 of the most popular v12 extensions).
As extension_builder is very influential in this area and is used to create extensions from scratch, it is useful to stick to the standard in this extension as well.
Related: TYPO3-Documentation/tea#802

[TASK] Use current standard for web-dir

---

Classes/Domain/Model/Extension.php

For non-composer-mode in certain cases the storagePath can not be determined. Add a default.
Fixes: #355

[BUGFIX] Add default for Extension::getStoragePath()

---

Classes/Configuration/ExtensionBuilderConfigurationManager.php

After deleting a relation wire I got this error:
`Extension could not be saved: PHP Warning: Undefined array key 22 in /html/typo3/typo3conf/ext/extension_builder/Classes/Configuration/ExtensionBuilderConfigurationManager.php line 431`
PHP 8.2
This change seems to work.

[BUGFIX] Undefined array key

---

.github/workflows/linters.yml
.github/workflows/publish.yml
.github/workflows/tests.yml

This avoids the warning:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, actions/cache@v1

[TASK] Update action/checkout and action/cache

---

composer.json

This setting is not considered anymore, see:
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/FileStructure/ComposerJson.html#replace-with-ext-key-self-version

[TASK] Remove "replace" section in composer.json

---

composer.json

They default is "dist" since Composer 2.1, so this setting is superfluous now: https://getcomposer.org/doc/06-config.md#preferred-install

[TASK] Remove preferred-install setting from composer.json

---

Tests/BaseFunctionalTest.php
Tests/Functional/FileGenerator/Property/GeneratedPropertyTest.php
Tests/Functional/Service/FileGeneratorTest.php
composer.json

sebastian/diff is not used in extension builder directly, so it can be removed. It is a transitive dependency of phpunit.
It paves the way to use a newer version of this package and unlocks the usage of phpunit v9.
Some deprecations introduced with phpunit v9 were solved.

[TASK] Update phpunit to v9.6

---

Tests/Functional/FileGenerator/Property/GeneratedPropertyTest.php
Tests/Functional/Service/FileGeneratorTest.php

PhpStorm complains about it:
Warning:(65, 20) Redundant character escape '\@' in RegExp

[TASK] Do not escape @ character in regular expressions
